### ISSUE TITLE
Admin Commands

### ISSUE THREAD

**Issue by uiruza** [Ice-Cream-Team/VanillaBot#23]
Setting commands to only be ran by selected UserIDs

**Comment by andrewandrepowell** [comment]
I propose all admin commands should have the following form: `!vb admin {command}`

**Comment by TooManyJohns** [comment]
Spitballing with Andrew for command ideas:
killing the bot
karma system (or any system in general implemented) reset
disable automute feature (might be implemented in the future)

**Comment by andrewandrepowell** [comment]
I know this was a while ago, but can you explain your idea of the "disable automute" feature @TooManyJohns, preferably in its own issue?

**Comment by TooManyJohns** [comment]
couple notes:

We should get into the habit of letting a user know they input a wrong command/blank command, this happened with the poll command where undefined inputs are a bit confusing for a user to comphrend
!vb owner admin !vb/all <-- possibilities?

also @andrewandrepowell i actually forget what i was talking about 🤔
