### ISSUE TITLE
Develop regression system for testing bot for continuous integration

### ISSUE THREAD

**Issue by andrewandrepowell** [Ice-Cream-Team/VanillaBot#24]
Once we start to have many commands, it will likely become impractical for the developer to always run every command before he completes the pull request. I propose a two part solution. 

First of all, I think we should add a `!vb regress` command that will run a test script that runs every command. Each command will be required to call a success function, which the regress command will use to determine whether or not the tested command was successfully. The `!vb regress` command should be made into an admin command #23. 

The second part will involve implementing an automated CI system (e.g. Jenkins or Travis or GitHub), which will execute upon PRs.

**Comment by TooManyJohns** [comment]
Notes:

- Eventually add auto-input for certain commands that need additional inputs (ex: !vb mal anime TEST)
