### ISSUE TITLE
Gamedig Implementation

### ISSUE THREAD

**Issue by TooManyJohns** [Ice-Cream-Team/VanillaBot#8]
Get the status of server for different games using Gamedig.
https://www.npmjs.com/package/gamedig   <--- cool info

**Comment by TooManyJohns** [comment]
in latest PR, @uiruza wants to take it further, i'll also advice the work done on this section of the project. maybe add more options/quality of life improvements

**Comment by uiruza** [comment]
Have converted msg.channel.send to embed messages. Working on editing colors to show if the server is down.
